"""add pr_number to artifact_versions

Revision ID: abd80c7121fe
Revises: d047b8eeb635
Create Date: 2026-07-28 13:48:37.394872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abd80c7121fe'
down_revision: Union[str, Sequence[str], None] = 'd047b8eeb635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifact_versions', sa.Column('pr_number', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'artifact_versions', ['pr_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artifact_versions', type_='unique')
    op.drop_column('artifact_versions', 'pr_number')
    # ### end Alembic commands ###
