ELEMENT_TYPES_BY_LAYER: dict[str, set[str]] = {
    "motivation": {
        "Stakeholder",
        "Driver",
        "Assessment",
        "Goal",
        "Outcome",
        "Principle",
        "Requirement",
        "Constraint",
        "Meaning",
        "Value",
    },
    "strategy": {
        "Resource",
        "Capability",
        "Course of Action",
        "Value Stream",
    },
    "business": {
        "Business Actor",
        "Business Role",
        "Business Collaboration",
        "Business Interface",
        "Business Process",
        "Business Function",
        "Business Interaction",
        "Business Event",
        "Business Service",
        "Business Object",
        "Contract",
        "Representation",
        "Product",
    },
    "application": {
        "Application Component",
        "Application Collaboration",
        "Application Interface",
        "Application Function",
        "Application Interaction",
        "Application Process",
        "Application Event",
        "Application Service",
        "Data Object",
    },
    "technology": {
        "Node",
        "Device",
        "System Software",
        "Technology Collaboration",
        "Technology Interface",
        "Path",
        "Communication Network",
        "Technology Function",
        "Technology Process",
        "Technology Interaction",
        "Technology Event",
        "Technology Service",
        "Artifact",
        "Equipment",
        "Facility",
        "Distribution Network",
        "Material",
    },
}

LAYERS: set[str] = set(ELEMENT_TYPES_BY_LAYER.keys())

ALL_ELEMENT_TYPES: set[str] = {
    element_type for types in ELEMENT_TYPES_BY_LAYER.values() for element_type in types
}
RELATIONSHIP_TYPES: set[str] = {
    "Composition",
    "Aggregation",
    "Assignment",
    "Realization",
    "Serving",
    "Access",
    "Influence",
    "Triggering",
    "Flow",
    "Specialization",
    "Association",
}
